### ISSUE TITLE
Can't compile on MacOS 11.3 Apple Silicon

### ISSUE THREAD

**Issue by aminta** [libretro/daphne#46]
6 warnings generated.
cc -DOSX -O2 -DNDEBUG -std=c99 -Wall -pedantic -fPIC -mmacosx-version-min=10.1 -I. -I./deps/libogg/include -I./deps/libvorbis/include -I./daphne/include -I./daphne/daphne-1.0-src/vldp2/include -I./deps/libvorbis/lib -I./daphne/libretro  -D__LIBRETRO__ -fPIC -mmacosx-version-min=10.1 -c -o daphne/src/atomic/SDL_atomic.o daphne/src/atomic/SDL_atomic.c
cc -DOSX -O2 -DNDEBUG -std=c99 -Wall -pedantic -fPIC -mmacosx-version-min=10.1 -I. -I./deps/libogg/include -I./deps/libvorbis/include -I./daphne/include -I./daphne/daphne-1.0-src/vldp2/include -I./deps/libvorbis/lib -I./daphne/libretro  -D__LIBRETRO__ -fPIC -mmacosx-version-min=10.1 -c -o daphne/src/atomic/SDL_spinlock.o daphne/src/atomic/SDL_spinlock.c
daphne/src/atomic/SDL_spinlock.c:90:12: error: implicit declaration of function 'OSAtomicCompareAndSwap32Barrier' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return OSAtomicCompareAndSwap32Barrier(0, 1, lock);
           ^
1 error generated.
make: *** [daphne/src/atomic/SDL_spinlock.o] Error 1
